name: tracal
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  drift: ^2.2.0
  sqlite3_flutter_libs:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.1
  path: ^1.8.2
  path_provider: ^2.0.11
  pluto_grid: ^5.4.2
  date_format: ^2.0.7
  data_table_2: ^2.3.8

dev_dependencies:
  build_runner: ^2.3.2
  drift_dev: ^2.2.0+1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
